color0 #424750
color1 #ffb4ab
color2 #a3c9ff
color3 #b6c8e4
color4 #eeb2f8
color5 #a3c9ff
color6 #b6c8e4
color7 #e2e2e7
color8 #8c919b
color9 #ffb4ab
color10 #a3c9ff
color11 #b6c8e4
color12 #eeb2f8
color13 #a3c9ff
color14 #b6c8e4
color15 #e2e2e7

cursor                #e2e2e7
cursor_text_color     #111317
background            #111317
foreground            #e2e2e7
selection_foreground  #c2c6d1
selection_background  #424750
active_border_color   #a3c9ff
inactive_border_color #424750
url_color             #a3c9ff

active_tab_foreground   #00315c
active_tab_background   #a3c9ff
inactive_tab_foreground #c2c6d1
inactive_tab_background #424750
cursor_trail_color      #c2c6d1
